# Generated by Django 3.2.6 on 2021-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210806_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cur',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lan',
            new_name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='suprehost',
            field=models.BooleanField(default=False),
        ),
    ]
