# Generated by Django 3.2.6 on 2021-09-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Github', 'Github'), ('Kakao', 'Kakao')], default='Email', max_length=50),
        ),
    ]
