# Generated by Django 3.2.6 on 2021-09-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedday',
            options={'verbose_name': 'Booked Day', 'verbose_name_plural': 'Booked Days'},
        ),
    ]
